### ISSUE TITLE
robot and infrastructure setup

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/lamor15#1]
# Robots
- [x] set up "lindanet" wifi to connect all robots to
- [x] create user "lamor" on all robots
- [x] create shared home dir for lamor user
- [x] create network setup, via script (as in https://gist.github.com/cburbridge/3ee13fb45a4f05ea7e1e)
- [x] check hardware config and complete it (e.g. second PC on Lucie)
- [x] install all packages
- [x] label all hardware
# software setup
- [x] one repository with basic tutorials and packages that people should fork (including different packages for the tutorials): https://github.com/strands-project/lamor15 
- [x] create launch files (same for all of them) using environment variables for hostnames so they work on each robot
- [x] create a launch file for simulation on localhost
- [x] create a simulation map of the David Chiddick building
- [x] adopt the human simulation to that environment

**Comment by marc-hanheide** [comment]
I suggest to also link [this gist](https://gist.github.com/marc-hanheide/1ac6d9dfd6e89d4f6126) as an easy way to setup their local machines env variables to connect to the robot.

**Comment by mzillich** [comment]
So https://github.com/strands-project/lamor15 should be where all the tutorials are collected, right?

**Comment by marc-hanheide** [comment]
yes, I'll be sending out an email shortly... Just preparing everything.

**Comment by marc-hanheide** [comment]
@strands-project/lamor_delivery_team 

I suggest the following strategy for robot setup, to be replicated on each robot:
- create a `lamor` user (non-admin, this is for the participants to use), UID must be the same on all computers, e.g. 2000, and also GID 2000
- also create a `lamor-admin` (admin!) user for us to use to administrate the robots (UID/GID 2001)
- NFS-share the home directory for the lamor user only between the different computers
- create a `.bashrc` for that user setting robotic-specific env variables that will be used in generic tmux / launch files
- create a `robot-network.sh` script, by adopting https://gist.github.com/cburbridge/3ee13fb45a4f05ea7e1e which sets all the NAT and IP forwarding correctly.
- update all packages to the latest released ones on all computers.

**Comment by cburbridge** [comment]
That sounds ok, it won't effect the "strands" account or any of the files we have in /opt. Robotnet is already setup on Bob & Betty, but you will need to disable the proxy server. It is set from the GUI on both, and set for apt-get on most too (perhaps not on Bob-R).

**Comment by cdondrup** [comment]
To quote @OMARI1988:

> I think the demo Paul was doing in the review meeting has some issues with the latest update of QSR lib. So if that is not included in the summer school then I think it should be fine.

Currently, @yianni and I are planning to base our tutorial and task on the newest version of QSR lib, see [milestone v0.2](https://github.com/strands-project/strands_qsr_lib/milestones/QSRlib%20v0.2) if this is a problem for @PDuckworth (who is not listed in any team associated with this repository so I hope he gets notified) we would have to discuss this and see if his code is easy to fix, which I beliefe would be the case, or we use an older version of the lib for the school.

**Comment by gatsoulis** [comment]
Currently Lucie's catkin runs an older version of QSRlib for Paul's code to be compatible. Depends also to what extend we use the robots. And also depends whether it might be faster/easier to just make people_tracker publish a track of poses which can be turned easily in QSRlib input rather than changing Paul;s code.

**Comment by cdondrup** [comment]
I do think that we want to use the robots as much as possible and all the packages should be the same version on all the robots. It also depends on if we want to use Paul's code or not. In general I would be in favour of having the latest version of everything installed for the summer school.

**Comment by marc-hanheide** [comment]
:+1: for having the latest version on all robots. It's gonna be a big hassle otherwise.

**Comment by marc-hanheide** [comment]
documented here: https://github.com/strands-project/lamor15/wiki/Robot-configuration

**Comment by PDuckworth** [comment]
Sorry, I just returned home from vacation. I hope any issues with QSRLib and my code were sorted out / you went ahead anyway and it didn't effect much :) 
I'll discuss with @yianni on Monday for a full update :) 

PS Yianni and I discussed the update to QSRLib which wouldn't work with my code, but I didn't have time to do much about it before I left.

**Comment by cdondrup** [comment]
No worries. Everything went fine :)
