### ISSUE TITLE
create sim environment of David Chiddick

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/lamor15#2]

**Comment by mzillich** [comment]
Do we need simulation of object recognition? This would mean learning objects for the simulator, which is tricky.

**Comment by marc-hanheide** [comment]
Well, I really don't know what you planned to do. That's what makes me struggle to provide a good answer here. I agree, that the CV part is probably not good for simulation. So, I'm happy for you to run that solely on the robot. Could you fill https://github.com/strands-project/lamor15/wiki#day-3---298-computer-vision so we have a better understanding of what you'll be trying to achieve? And discuss how it fits in the big picture. I'm happy to have a hangout/skype on this today to discuss in greater detail.

**Comment by Jailander** [comment]
this pr finishes the model https://github.com/strands-project/strands_morse/pull/135

**Comment by marc-hanheide** [comment]
I have re-released strands_morse, so it's all there now.
