### ISSUE TITLE
write general instructions about using our robots

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/lamor15#9]
put this here: https://github.com/strands-project/lamor15/wiki/Working-with-the-STRANDS-robots

cover things like 
- [x] responsibilities: 
  - Never let the robot unobserved without the emergency stop disengaged!
  - Always put the robot to charge when not used
  - Handle with care!
- [x] logins (user `lamor`, don't put the password here as it's a public repo)
- [x] remote login 
- [x] basic commands and using tmux (the most important tmux commands as well) to start the different - [ ] emergency stop, and how to use the joystick (basic commands, incl docking, etc)
- [x] calibration etc (chest cam)
- [x] links to useful packages: `strands_webserver`, `mary_tts`, etc...

**Comment by cdondrup** [comment]
Aye aye!

**Comment by cdondrup** [comment]
Done, only needs the instructions on how to launch the simulation. Will add when the sim is merged and finalised.

**Comment by marc-hanheide** [comment]
I think a little more info on ssh and side PCs might be useful, but otherwise, excellent.
